
components = "Influent, Anaerobic, Anoxic, Aerobic, Clarifier".replace(" ", "").split(",")
states = "S_A, S_ALK, S_F, S_I, S_N2, S_NH4, S_NO3, S_O2, S_PO4, X_AUT, X_H, X_I, X_PAO, X_PHA, X_PP, X_S, X_TSS".replace(" ", "").split(",")

def get_chem_reaction(S_A, S_ALK, S_F, S_I, S_N2, S_NH4, S_NO3, S_O2, S_PO4, 
	X_AUT, X_H, X_I, X_PAO, X_PHA, X_PP, X_S, X_TSS, DO_given, 
        with_aeration):

	b_AUT = 0.15
	b_H = 0.4
	b_PAO = 0.2
	b_PHA = 0.2
	b_PP = 0.2
	#DO = 3
	DO = DO_given
	f_SI = 0
	f_XI = 0.1
	Inflow_S_A = 20
	Inflow_S_ALK = 500
	Inflow_S_F = 30
	Inflow_S_I = 30
	Inflow_S_N2 = 15
	Inflow_S_NH4 = 16
	Inflow_S_NO3 = 0
	Inflow_S_O2 = 0
	Inflow_S_PO4 = 3.6
	Inflow_X_AUT = 0
	Inflow_X_H = 30
	Inflow_X_I = 25
	Inflow_X_PAO = 0
	Inflow_X_PHA = 0
	Inflow_X_PP = 0
	Inflow_X_S = 125
	Inflow_X_TSS = 180
	i_NBM = 0.07
	i_NSF = 0.03
	i_NSI = 0.01
	i_NXI = 0.03
	i_NXS = 0.04
	i_PBM = 0.02
	i_PSF = 0.01
	i_PSI = 0
	i_PXI = 0.01
	i_PXS = 0.01
	i_TSSBM = 0.9
	i_TSSXI = 0.75
	i_TSSXS = 0.75
	K_A = 4
	K_ALK = 0.1
	K_ALK_aut = 0.5
	K_F = 4
	K_fe = 4
	K_h = 3
	K_IPP = 0.02
	K_MAX = 0.34
	K_NH4 = 0.05
	K_NH4_aut = 1
	K_NO3 = 0.5
	K_O2 = 0.2
	K_O2_aut = 0.5
	K_P = 0.01
	K_PHA = 0.01
	K_PP = 0.01
	K_PS = 0.2
	K_X = 0.1
	n_fe = 0.4
	n_NO3_het = 0.8
	n_NO3_hyd = 0.6
	n_NO3_pao = 0.6
	Qin = 24
	Qinter = 1*Qin
	Qsludge = 0.2*Qin
	q_fe = 3
	q_PHA = 3
	q_PP = 1.5
	SRT = 12
	u_AUT = 1
	u_H = 6
	u_PAO = 1
	v15_PO4 = -(f_XI*i_PXI+(1-f_XI)*i_PXS-i_PBM)
	v19_NH4 = -(f_XI*i_NXI+(1-f_XI)*i_NXS-i_NBM)
	v19_PO4 = -(f_XI*i_PXI+(1-f_XI)*i_PXS-i_PBM)
	v1_NH4 = -((1-f_SI)*i_NSF+f_SI*i_NSI-i_NXS)
	v1_PO4 = -((1-f_SI)*i_PSF+f_SI*i_PSI-i_PXS)
	v1_TSS = -i_TSSXS
	v2_NH4 = -((1-f_SI)*i_NSF+f_SI*i_NSI-i_NXS)
	v2_PO4 = -((1-f_SI)*i_PSF+f_SI*i_PSI-i_PXS)
	v2_TSS = -i_TSSXS
	v3_NH4 = -((1-f_SI)*i_NSF+f_SI*i_NSI-i_NXS)
	v3_PO4 = -((1-f_SI)*i_PSF+f_SI*i_PSI-i_PXS)
	v3_TSS = -i_TSSXS
	Y_AUT = 0.24
	Y_H = 0.625
	Y_PAO = 0.625
	Y_PHA = 0.2
	Y_PO4 = 0.4
	R01 = K_h*(S_O2/(K_O2+S_O2))*((X_S/X_H)/(K_X+X_S/X_H))*X_H
	R02 = K_h*n_NO3_hyd*(K_O2/(K_O2+S_O2))*(S_NO3/(K_NO3+S_NO3))*((X_S/X_H)/(K_X+X_S/X_H))*X_H
	R03 = K_h*n_fe*(K_O2/(K_O2+S_O2))*(K_NO3/(K_NO3+S_NO3))*((X_S/X_H)/(K_X+X_S/X_H))*X_H
	R04 = u_H*(S_O2/(K_O2+S_O2))*(S_F/(K_F+S_F))*(S_F/(S_F+S_A))*(S_NH4/(K_NH4+S_NH4))*(S_PO4/(K_P+S_PO4))*(S_ALK/(K_ALK+S_ALK))*X_H
	R05 = u_H*(S_O2/(K_O2+S_O2))*(S_A/(K_A+S_A))*(S_A/(S_F+S_A))*(S_NH4/(K_NH4+S_NH4))*(S_PO4/(K_P+S_PO4))*(S_ALK/(K_ALK+S_ALK))*X_H
	R06 = u_H*n_NO3_het*(K_O2/(K_O2+S_O2))*(S_F/(K_F+S_F))*(S_F/(S_F+S_A))*(S_NH4/(K_NH4+S_NH4))*(S_NO3/(K_NO3+S_NO3))*(S_ALK/(K_ALK+S_ALK))*(S_PO4/(K_P+S_PO4))*X_H
	R07 = u_H*n_NO3_het*(K_O2/(K_O2+S_O2))*(S_A/(K_A+S_A))*(S_A/(S_F+S_A))*(S_NH4/(K_NH4+S_NH4))*(S_NO3/(K_NO3+S_NO3))*(S_ALK/(K_ALK+S_ALK))*(S_PO4/(K_P+S_PO4))*X_H
	R08 = q_fe*(K_O2/(K_O2+S_O2))*(K_NO3/(K_NO3+S_NO3))*(S_F/(K_fe+S_F))*(S_ALK/(K_ALK+S_ALK))*X_H
	R09 = b_H*X_H
	R10 = q_PHA*(S_A/(K_A+S_A))*(S_ALK/(K_ALK+S_ALK))*((X_PP/X_PAO)/(K_PP+X_PP/X_PAO))*X_PAO
	R11 = q_PP*(S_O2/(K_O2+S_O2))*(S_PO4/(K_PS+S_PO4))*(S_ALK/(K_ALK+S_ALK))*((X_PHA/X_PAO)/(K_PHA+X_PHA/X_PAO))*((K_MAX-X_PP/X_PAO)/(K_IPP+K_MAX-X_PP/X_PAO))*X_PAO
	R12 = R11*n_NO3_pao*(K_O2/S_O2)*(S_NO3/(K_NO3+S_NO3))
	R13 = u_PAO*(S_O2/(K_O2+S_O2))*(S_NH4/(K_NH4+S_NH4))*(S_ALK/(K_ALK+S_ALK))*(S_PO4/(K_P+S_PO4))*((X_PHA/X_PAO)/(K_PHA+X_PHA/X_PAO))*X_PAO
	R14 = R13*n_NO3_pao*(K_O2/S_O2)*(S_NO3/(K_NO3+S_NO3))
	R15 = b_PAO*X_PAO*S_ALK/(K_ALK+S_ALK)
	R16 = b_PP*X_PP*S_ALK/(K_ALK+S_ALK)
	R17 = b_PHA*X_PHA*S_ALK/(K_ALK+S_ALK)
	R18 = u_AUT*(S_O2/(K_O2_aut+S_O2))*(S_NH4/(K_NH4_aut+S_NH4))*(S_PO4/(K_P+S_PO4))*(S_ALK/(K_ALK_aut+S_ALK))*X_AUT
	R19 = b_AUT*X_AUT
	v12_NO3 = -(7/20)*Y_PHA
	v13_O2 = 1-1/Y_H
	v14_NO3 = (7/20)*(1-1/Y_H)
	v18_NH4 = -i_NBM-1/Y_AUT
	v1_ALK = (1/14)*v1_NH4-(1.5/31)*v1_PO4
	v2_ALK = (1/14)*v2_NH4-(1.5/31)*v2_PO4
	v3_ALK = (1/14)*v3_NH4-(1.5/31)*v3_PO4
	d_S_A = 0
	d_S_ALK = 0
	d_S_F = 0
	d_S_I = 0
	d_S_N2 = 0
	d_S_NH4 = 0
	d_S_NO3 = 0
	d_S_O2 = 0
	d_S_PO4 = 0
	d_X_AUT = 0
	d_X_H = 0
	d_X_I = 0
	d_X_PAO = 0
	d_X_PHA = 0
	d_X_PP = 0
	d_X_S = 0
	d_X_TSS = 0
	if with_aeration:
		d_S_O2 += (10000*(DO-S_O2)) * (1)
	d_S_F += (R01) * (1-f_SI)
	d_S_NH4 += (R01) * (v1_NH4)
	d_S_PO4 += (R01) * (v1_PO4)
	d_S_I += (R01) * (f_SI)
	d_S_ALK += (R01) * (v1_ALK)
	d_X_S += (R01) * (-1)
	d_X_TSS += (R01) * (v1_TSS)
	d_S_F += (R02) * (1-f_SI)
	d_S_NH4 += (R02) * (v2_NH4)
	d_S_PO4 += (R02) * (v2_PO4)
	d_S_I += (R02) * (f_SI)
	d_S_ALK += (R02) * (v2_ALK)
	d_X_S += (R02) * (-1)
	d_X_TSS += (R02) * (v2_TSS)
	d_S_F += (R03) * (1-f_SI)
	d_S_NH4 += (R03) * (v3_NH4)
	d_S_PO4 += (R03) * (v3_PO4)
	d_S_I += (R03) * (f_SI)
	d_S_ALK += (R03) * (v3_ALK)
	d_X_S += (R03) * (-1)
	d_X_TSS += (R03) * (v3_TSS)
	d_S_O2 += (R04) * (1-1/Y_H)
	d_S_F += (R04) * (-1/Y_H)
	d_X_H += (R04) * (1)
	d_S_NH4 += (R04) * (i_NSF/Y_H-i_NBM)
	d_S_PO4 += (R04) * (i_PSF/Y_H-i_PBM)
	d_S_ALK += (R04) * (1/14*(i_NSF/Y_H-i_NBM)-(1.5/31)*(i_PSF/Y_H-i_PBM))
	d_X_TSS += (R04) * (i_TSSBM)
	d_S_O2 += (R05) * (1-1/Y_H)
	d_S_A += (R05) * (-1/Y_H)
	d_X_H += (R05) * (1)
	d_S_NH4 += (R05) * (-i_NBM)
	d_S_PO4 += (R05) * (-i_PBM)
	d_S_ALK += (R05) * ((1/64)*(1/Y_H)-(i_NBM/14)+(1.5*i_PBM)/31)
	d_X_TSS += (R05) * (i_TSSBM)
	d_S_F += (R06) * (-1/Y_H)
	d_S_NO3 += (R06) * (-(1-Y_H)/(2.86*Y_H))
	d_S_N2 += (R06) * ((1-Y_H)/(2.86*Y_H))
	d_X_H += (R06) * (1)
	d_S_NH4 += (R06) * (i_NSF/Y_H-i_NBM)
	d_S_PO4 += (R06) * (i_PSF/Y_H-i_PBM)
	d_S_ALK += (R06) * ((1/14)*((1-Y_H)/(2.86*Y_H))+(1/14)*(i_NSF/Y_H-i_NBM)-(1.5/31)*(i_PSF/Y_H-i_PBM))
	d_X_TSS += (R06) * (i_TSSBM)
	d_S_A += (R07) * (-1/Y_H)
	d_S_NO3 += (R07) * (-(1-Y_H)/(2.86*Y_H))
	d_S_N2 += (R07) * ((1-Y_H)/(2.86*Y_H))
	d_X_H += (R07) * (1)
	d_S_NH4 += (R07) * (-i_NBM)
	d_S_PO4 += (R07) * (-i_PBM)
	d_S_ALK += (R07) * ((1/64)*(1/Y_H)+(1/14)*((1-Y_H)/(2.86*Y_H))-(i_NBM/14)+(1.5*i_PBM/31))
	d_X_TSS += (R07) * (i_TSSBM)
	d_S_NH4 += (R08) * (i_NSF)
	d_S_F += (R08) * (-1)
	d_S_A += (R08) * (1)
	d_S_ALK += (R08) * (-1/64+(1/14)*i_NSF-(1.5/31)*i_PSF)
	d_S_PO4 += (R08) * (i_PSF)
	d_X_TSS += (R08) * (0)
	d_X_I += (R09) * (f_XI)
	d_X_S += (R09) * (1-f_XI)
	d_X_H += (R09) * (-1)
	d_S_PO4 += (R09) * (-i_PXI*f_XI-i_PXS*(1-f_XI)+i_PBM)
	d_S_ALK += (R09) * ((1/14)*(-i_NXI*f_XI-i_NXS*(1-f_XI)+i_NBM)-(1.5/31)*(-i_PXI*f_XI-i_PXS*(1-f_XI)+i_PBM))
	d_S_NH4 += (R09) * (-i_NXI*f_XI-i_NXS*(1-f_XI)+i_NBM)
	d_X_TSS += (R09) * (i_TSSXI*f_XI+i_TSSXS*(1-f_XI)-i_TSSBM)
	d_S_A += (R10) * (-1)
	d_S_PO4 += (R10) * (Y_PO4)
	d_X_PP += (R10) * (-Y_PO4)
	d_X_PHA += (R10) * (1)
	d_S_NH4 += (R10) * (0)
	d_S_ALK += (R10) * ((1/64)-(0.5/31)*Y_PO4)
	d_X_TSS += (R10) * (0.6-3.23*Y_PO4)
	d_S_O2 += (R11) * (-Y_PHA)
	d_S_PO4 += (R11) * (-1)
	d_X_PP += (R11) * (1)
	d_X_PHA += (R11) * (-Y_PHA)
	d_S_NH4 += (R11) * (0)
	d_S_ALK += (R11) * (0.5/31)
	d_X_TSS += (R11) * (3.23-0.6*Y_PHA)
	d_S_PO4 += (R12) * (-1)
	d_X_PP += (R12) * (1)
	d_X_PHA += (R12) * (-Y_PHA)
	d_S_NH4 += (R12) * (0)
	d_S_ALK += (R12) * (0.5/31-(1/14)*(v12_NO3))
	d_S_N2 += (R12) * (-v12_NO3)
	d_S_NO3 += (R12) * (v12_NO3)
	d_X_TSS += (R12) * (3.23-0.6*Y_PHA)
	d_S_O2 += (R13) * (v13_O2)
	d_S_PO4 += (R13) * (-i_PBM)
	d_X_PAO += (R13) * (1)
	d_X_PHA += (R13) * (-1/Y_PAO)
	d_S_NH4 += (R13) * (-i_NBM)
	d_S_ALK += (R13) * ((1.5/31)*i_PBM-(1/14)*i_NBM)
	d_X_TSS += (R13) * (i_TSSBM-0.6*(1/Y_H))
	d_S_PO4 += (R14) * (-i_PBM)
	d_X_PAO += (R14) * (1)
	d_X_PHA += (R14) * (-1/Y_PAO)
	d_S_NH4 += (R14) * (-i_NBM)
	d_S_ALK += (R14) * ((1.5/31)*i_PBM-(1/14)*i_NBM-(1/14)*v14_NO3)
	d_X_TSS += (R14) * (i_TSSBM-0.6*(1/Y_H))
	d_S_N2 += (R14) * (-v14_NO3)
	d_S_NO3 += (R14) * (v14_NO3)
	d_S_PO4 += (R15) * (v15_PO4)
	d_X_I += (R15) * (f_XI)
	d_X_S += (R15) * (1-f_XI)
	d_X_PAO += (R15) * (-1)
	d_S_NH4 += (R15) * (-i_NXI*f_XI-i_NXS*(1-f_XI)+i_NBM)
	d_S_ALK += (R15) * (-(1.5/31)*v15_PO4+(1/14)*(-i_NXI*f_XI-i_NXS*(1-f_XI)+i_NBM))
	d_X_TSS += (R15) * (i_TSSXI*f_XI+i_TSSXS*(1-f_XI)-i_TSSBM)
	d_S_PO4 += (R16) * (1)
	d_X_PP += (R16) * (-1)
	d_S_NH4 += (R16) * (0)
	d_S_ALK += (R16) * (-0.5/31)
	d_X_TSS += (R16) * (-3.23)
	d_S_A += (R17) * (1)
	d_X_PHA += (R17) * (-1)
	d_S_NH4 += (R17) * (0)
	d_S_ALK += (R17) * (-1/64)
	d_X_TSS += (R17) * (-0.6)
	d_S_O2 += (R18) * (-(4.57-Y_AUT)/Y_AUT)
	d_S_NH4 += (R18) * (v18_NH4)
	d_S_NO3 += (R18) * (1/Y_AUT)
	d_S_PO4 += (R18) * (-i_PBM)
	d_X_AUT += (R18) * (1)
	d_S_ALK += (R18) * (-(1/14)*i_NBM-(2/(14*Y_AUT))+(1.5/31)*i_PBM)
	d_X_TSS += (R18) * (i_TSSBM)
	d_S_NH4 += (R19) * (v19_NH4)
	d_S_PO4 += (R19) * (v19_PO4)
	d_X_I += (R19) * (f_XI)
	d_X_S += (R19) * (1-f_XI)
	d_X_AUT += (R19) * (-1)
	d_S_ALK += (R19) * ((1/14)*v19_NH4-(1.5/31)*v19_PO4)
	d_X_TSS += (R19) * (i_TSSXI*f_XI+i_TSSXS*(1-f_XI)-i_TSSBM)

	return d_S_A, d_S_ALK, d_S_F, d_S_I, d_S_N2, d_S_NH4, d_S_NO3, d_S_O2, d_S_PO4, d_X_AUT, d_X_H, d_X_I, d_X_PAO, d_X_PHA, d_X_PP, d_X_S, d_X_TSS


def get_mass_flow(Influent_S_A, Influent_S_ALK, Influent_S_F, Influent_S_I, Influent_S_N2, Influent_S_NH4, Influent_S_NO3, Influent_S_O2, Influent_S_PO4, Influent_X_AUT, Influent_X_H, Influent_X_I, Influent_X_PAO, Influent_X_PHA, Influent_X_PP, Influent_X_S, Influent_X_TSS, Anaerobic_S_A, Anaerobic_S_ALK, Anaerobic_S_F, Anaerobic_S_I, Anaerobic_S_N2, Anaerobic_S_NH4, Anaerobic_S_NO3, Anaerobic_S_O2, Anaerobic_S_PO4, Anaerobic_X_AUT, Anaerobic_X_H, Anaerobic_X_I, Anaerobic_X_PAO, Anaerobic_X_PHA, Anaerobic_X_PP, Anaerobic_X_S, Anaerobic_X_TSS, Anoxic_S_A, Anoxic_S_ALK, Anoxic_S_F, Anoxic_S_I, Anoxic_S_N2, Anoxic_S_NH4, Anoxic_S_NO3, Anoxic_S_O2, Anoxic_S_PO4, Anoxic_X_AUT, Anoxic_X_H, Anoxic_X_I, Anoxic_X_PAO, Anoxic_X_PHA, Anoxic_X_PP, Anoxic_X_S, Anoxic_X_TSS, Aerobic_S_A, Aerobic_S_ALK, Aerobic_S_F, Aerobic_S_I, Aerobic_S_N2, Aerobic_S_NH4, Aerobic_S_NO3, Aerobic_S_O2, Aerobic_S_PO4, Aerobic_X_AUT, Aerobic_X_H, Aerobic_X_I, Aerobic_X_PAO, Aerobic_X_PHA, Aerobic_X_PP, Aerobic_X_S, Aerobic_X_TSS, Clarifier_S_A, Clarifier_S_ALK, Clarifier_S_F, Clarifier_S_I, Clarifier_S_N2, Clarifier_S_NH4, Clarifier_S_NO3, Clarifier_S_O2, Clarifier_S_PO4, Clarifier_X_AUT, Clarifier_X_H, Clarifier_X_I, Clarifier_X_PAO, Clarifier_X_PHA, Clarifier_X_PP, Clarifier_X_S, Clarifier_X_TSS, Qin, Qsludge, Qinter, Inflow_S_A, Inflow_S_ALK, Inflow_S_F, Inflow_S_I, Inflow_S_N2, Inflow_S_NH4, Inflow_S_NO3, Inflow_S_O2, Inflow_S_PO4, Inflow_X_AUT, Inflow_X_H, Inflow_X_I, Inflow_X_PAO, Inflow_X_PHA, Inflow_X_PP, Inflow_X_S, Inflow_X_TSS, SRT):
	d_Influent_S_A = 0
	d_Influent_S_ALK = 0
	d_Influent_S_F = 0
	d_Influent_S_I = 0
	d_Influent_S_N2 = 0
	d_Influent_S_NH4 = 0
	d_Influent_S_NO3 = 0
	d_Influent_S_O2 = 0
	d_Influent_S_PO4 = 0
	d_Influent_X_AUT = 0
	d_Influent_X_H = 0
	d_Influent_X_I = 0
	d_Influent_X_PAO = 0
	d_Influent_X_PHA = 0
	d_Influent_X_PP = 0
	d_Influent_X_S = 0
	d_Influent_X_TSS = 0
	d_Anaerobic_S_A = 0
	d_Anaerobic_S_ALK = 0
	d_Anaerobic_S_F = 0
	d_Anaerobic_S_I = 0
	d_Anaerobic_S_N2 = 0
	d_Anaerobic_S_NH4 = 0
	d_Anaerobic_S_NO3 = 0
	d_Anaerobic_S_O2 = 0
	d_Anaerobic_S_PO4 = 0
	d_Anaerobic_X_AUT = 0
	d_Anaerobic_X_H = 0
	d_Anaerobic_X_I = 0
	d_Anaerobic_X_PAO = 0
	d_Anaerobic_X_PHA = 0
	d_Anaerobic_X_PP = 0
	d_Anaerobic_X_S = 0
	d_Anaerobic_X_TSS = 0
	d_Anoxic_S_A = 0
	d_Anoxic_S_ALK = 0
	d_Anoxic_S_F = 0
	d_Anoxic_S_I = 0
	d_Anoxic_S_N2 = 0
	d_Anoxic_S_NH4 = 0
	d_Anoxic_S_NO3 = 0
	d_Anoxic_S_O2 = 0
	d_Anoxic_S_PO4 = 0
	d_Anoxic_X_AUT = 0
	d_Anoxic_X_H = 0
	d_Anoxic_X_I = 0
	d_Anoxic_X_PAO = 0
	d_Anoxic_X_PHA = 0
	d_Anoxic_X_PP = 0
	d_Anoxic_X_S = 0
	d_Anoxic_X_TSS = 0
	d_Aerobic_S_A = 0
	d_Aerobic_S_ALK = 0
	d_Aerobic_S_F = 0
	d_Aerobic_S_I = 0
	d_Aerobic_S_N2 = 0
	d_Aerobic_S_NH4 = 0
	d_Aerobic_S_NO3 = 0
	d_Aerobic_S_O2 = 0
	d_Aerobic_S_PO4 = 0
	d_Aerobic_X_AUT = 0
	d_Aerobic_X_H = 0
	d_Aerobic_X_I = 0
	d_Aerobic_X_PAO = 0
	d_Aerobic_X_PHA = 0
	d_Aerobic_X_PP = 0
	d_Aerobic_X_S = 0
	d_Aerobic_X_TSS = 0
	d_Clarifier_S_A = 0
	d_Clarifier_S_ALK = 0
	d_Clarifier_S_F = 0
	d_Clarifier_S_I = 0
	d_Clarifier_S_N2 = 0
	d_Clarifier_S_NH4 = 0
	d_Clarifier_S_NO3 = 0
	d_Clarifier_S_O2 = 0
	d_Clarifier_S_PO4 = 0
	d_Clarifier_X_AUT = 0
	d_Clarifier_X_H = 0
	d_Clarifier_X_I = 0
	d_Clarifier_X_PAO = 0
	d_Clarifier_X_PHA = 0
	d_Clarifier_X_PP = 0
	d_Clarifier_X_S = 0
	d_Clarifier_X_TSS = 0
	#inflow to Influent
	d_Influent_X_I += (Qin*Inflow_X_I)/1
	d_Influent_S_O2 += (Qin*Inflow_S_O2)/1
	d_Influent_S_F += (Qin*Inflow_S_F)/1
	d_Influent_S_A += (Qin*Inflow_S_A)/1
	d_Influent_S_NH4 += (Qin*Inflow_S_NH4)/1
	d_Influent_S_NO3 += (Qin*Inflow_S_NO3)/1
	d_Influent_S_I += (Qin*Inflow_S_I)/1
	d_Influent_S_ALK += (Qin*Inflow_S_ALK)/1
	d_Influent_S_N2 += (Qin*Inflow_S_N2)/1
	d_Influent_X_S += (Qin*Inflow_X_S)/1
	d_Influent_X_PAO += (Qin*Inflow_X_PAO)/1
	d_Influent_X_PP += (Qin*Inflow_X_PP)/1
	d_Influent_X_PHA += (Qin*Inflow_X_PHA)/1
	d_Influent_X_H += (Qin*Inflow_X_H)/1
	d_Influent_X_AUT += (Qin*Inflow_X_AUT)/1
	d_Influent_X_TSS += (Qin*Inflow_X_TSS)/1
	d_Influent_S_PO4 += (Qin*Inflow_S_PO4)/1
	#outflow from Influent
	d_Influent_X_I -= (Qin) * Influent_X_I/1
	d_Influent_S_O2 -= (Qin) * Influent_S_O2/1
	d_Influent_S_F -= (Qin) * Influent_S_F/1
	d_Influent_S_A -= (Qin) * Influent_S_A/1
	d_Influent_S_NH4 -= (Qin) * Influent_S_NH4/1
	d_Influent_S_NO3 -= (Qin) * Influent_S_NO3/1
	d_Influent_S_I -= (Qin) * Influent_S_I/1
	d_Influent_S_ALK -= (Qin) * Influent_S_ALK/1
	d_Influent_S_N2 -= (Qin) * Influent_S_N2/1
	d_Influent_X_S -= (Qin) * Influent_X_S/1
	d_Influent_X_PAO -= (Qin) * Influent_X_PAO/1
	d_Influent_X_PP -= (Qin) * Influent_X_PP/1
	d_Influent_X_PHA -= (Qin) * Influent_X_PHA/1
	d_Influent_X_H -= (Qin) * Influent_X_H/1
	d_Influent_X_AUT -= (Qin) * Influent_X_AUT/1
	d_Influent_X_TSS -= (Qin) * Influent_X_TSS/1
	d_Influent_S_PO4 -= (Qin) * Influent_S_PO4/1
	#inflow from Influent to Anaerobic
	d_Anaerobic_X_I += (Qin) * Influent_X_I/2
	d_Anaerobic_S_O2 += (Qin) * Influent_S_O2/2
	d_Anaerobic_S_F += (Qin) * Influent_S_F/2
	d_Anaerobic_S_A += (Qin) * Influent_S_A/2
	d_Anaerobic_S_NH4 += (Qin) * Influent_S_NH4/2
	d_Anaerobic_S_NO3 += (Qin) * Influent_S_NO3/2
	d_Anaerobic_S_I += (Qin) * Influent_S_I/2
	d_Anaerobic_S_ALK += (Qin) * Influent_S_ALK/2
	d_Anaerobic_S_N2 += (Qin) * Influent_S_N2/2
	d_Anaerobic_X_S += (Qin) * Influent_X_S/2
	d_Anaerobic_X_PAO += (Qin) * Influent_X_PAO/2
	d_Anaerobic_X_PP += (Qin) * Influent_X_PP/2
	d_Anaerobic_X_PHA += (Qin) * Influent_X_PHA/2
	d_Anaerobic_X_H += (Qin) * Influent_X_H/2
	d_Anaerobic_X_AUT += (Qin) * Influent_X_AUT/2
	d_Anaerobic_X_TSS += (Qin) * Influent_X_TSS/2
	d_Anaerobic_S_PO4 += (Qin) * Influent_S_PO4/2
	#inflow from Clarifier to Anaerobic
	Q = (Qin - 12/SRT + Qsludge) 
	d_Anaerobic_S_A += Qsludge*Clarifier_S_A/2
	d_Anaerobic_S_ALK += Qsludge*Clarifier_S_ALK/2
	d_Anaerobic_S_F += Qsludge*Clarifier_S_F/2
	d_Anaerobic_S_I += Qsludge*Clarifier_S_I/2
	d_Anaerobic_S_N2 += Qsludge*Clarifier_S_N2/2
	d_Anaerobic_S_NH4 += Qsludge*Clarifier_S_NH4/2
	d_Anaerobic_S_NO3 += Qsludge*Clarifier_S_NO3/2
	d_Anaerobic_S_O2 += Qsludge*Clarifier_S_O2/2
	d_Anaerobic_S_PO4 += Qsludge*Clarifier_S_PO4/2
	d_Anaerobic_X_AUT += Q*Clarifier_X_AUT/2
	d_Anaerobic_X_H += Q*Clarifier_X_H/2
	d_Anaerobic_X_I += Q*Clarifier_X_I/2
	d_Anaerobic_X_PAO += Q*Clarifier_X_PAO/2
	d_Anaerobic_X_PHA += Q*Clarifier_X_PHA/2
	d_Anaerobic_X_PP += Q*Clarifier_X_PP/2
	d_Anaerobic_X_S += Q*Clarifier_X_S/2
	d_Anaerobic_X_TSS += Q*Clarifier_X_TSS/2
	#outflow from Anaerobic
	d_Anaerobic_X_I -= (Qin + Qsludge) * Anaerobic_X_I/2
	d_Anaerobic_S_O2 -= (Qin + Qsludge) * Anaerobic_S_O2/2
	d_Anaerobic_S_F -= (Qin + Qsludge) * Anaerobic_S_F/2
	d_Anaerobic_S_A -= (Qin + Qsludge) * Anaerobic_S_A/2
	d_Anaerobic_S_NH4 -= (Qin + Qsludge) * Anaerobic_S_NH4/2
	d_Anaerobic_S_NO3 -= (Qin + Qsludge) * Anaerobic_S_NO3/2
	d_Anaerobic_S_I -= (Qin + Qsludge) * Anaerobic_S_I/2
	d_Anaerobic_S_ALK -= (Qin + Qsludge) * Anaerobic_S_ALK/2
	d_Anaerobic_S_N2 -= (Qin + Qsludge) * Anaerobic_S_N2/2
	d_Anaerobic_X_S -= (Qin + Qsludge) * Anaerobic_X_S/2
	d_Anaerobic_X_PAO -= (Qin + Qsludge) * Anaerobic_X_PAO/2
	d_Anaerobic_X_PP -= (Qin + Qsludge) * Anaerobic_X_PP/2
	d_Anaerobic_X_PHA -= (Qin + Qsludge) * Anaerobic_X_PHA/2
	d_Anaerobic_X_H -= (Qin + Qsludge) * Anaerobic_X_H/2
	d_Anaerobic_X_AUT -= (Qin + Qsludge) * Anaerobic_X_AUT/2
	d_Anaerobic_X_TSS -= (Qin + Qsludge) * Anaerobic_X_TSS/2
	d_Anaerobic_S_PO4 -= (Qin + Qsludge) * Anaerobic_S_PO4/2
	#inflow from Anaerobic to Anoxic
	d_Anoxic_X_I += (Qin + Qsludge) * Anaerobic_X_I/4
	d_Anoxic_S_O2 += (Qin + Qsludge) * Anaerobic_S_O2/4
	d_Anoxic_S_F += (Qin + Qsludge) * Anaerobic_S_F/4
	d_Anoxic_S_A += (Qin + Qsludge) * Anaerobic_S_A/4
	d_Anoxic_S_NH4 += (Qin + Qsludge) * Anaerobic_S_NH4/4
	d_Anoxic_S_NO3 += (Qin + Qsludge) * Anaerobic_S_NO3/4
	d_Anoxic_S_I += (Qin + Qsludge) * Anaerobic_S_I/4
	d_Anoxic_S_ALK += (Qin + Qsludge) * Anaerobic_S_ALK/4
	d_Anoxic_S_N2 += (Qin + Qsludge) * Anaerobic_S_N2/4
	d_Anoxic_X_S += (Qin + Qsludge) * Anaerobic_X_S/4
	d_Anoxic_X_PAO += (Qin + Qsludge) * Anaerobic_X_PAO/4
	d_Anoxic_X_PP += (Qin + Qsludge) * Anaerobic_X_PP/4
	d_Anoxic_X_PHA += (Qin + Qsludge) * Anaerobic_X_PHA/4
	d_Anoxic_X_H += (Qin + Qsludge) * Anaerobic_X_H/4
	d_Anoxic_X_AUT += (Qin + Qsludge) * Anaerobic_X_AUT/4
	d_Anoxic_X_TSS += (Qin + Qsludge) * Anaerobic_X_TSS/4
	d_Anoxic_S_PO4 += (Qin + Qsludge) * Anaerobic_S_PO4/4
	#inflow from Aerobic to Anoxic
	d_Anoxic_X_I += (Qinter) * Aerobic_X_I/4
	d_Anoxic_S_O2 += (Qinter) * Aerobic_S_O2/4
	d_Anoxic_S_F += (Qinter) * Aerobic_S_F/4
	d_Anoxic_S_A += (Qinter) * Aerobic_S_A/4
	d_Anoxic_S_NH4 += (Qinter) * Aerobic_S_NH4/4
	d_Anoxic_S_NO3 += (Qinter) * Aerobic_S_NO3/4
	d_Anoxic_S_I += (Qinter) * Aerobic_S_I/4
	d_Anoxic_S_ALK += (Qinter) * Aerobic_S_ALK/4
	d_Anoxic_S_N2 += (Qinter) * Aerobic_S_N2/4
	d_Anoxic_X_S += (Qinter) * Aerobic_X_S/4
	d_Anoxic_X_PAO += (Qinter) * Aerobic_X_PAO/4
	d_Anoxic_X_PP += (Qinter) * Aerobic_X_PP/4
	d_Anoxic_X_PHA += (Qinter) * Aerobic_X_PHA/4
	d_Anoxic_X_H += (Qinter) * Aerobic_X_H/4
	d_Anoxic_X_AUT += (Qinter) * Aerobic_X_AUT/4
	d_Anoxic_X_TSS += (Qinter) * Aerobic_X_TSS/4
	d_Anoxic_S_PO4 += (Qinter) * Aerobic_S_PO4/4
	#outflow from Anoxic
	d_Anoxic_X_I -= (Qin + Qsludge + Qinter) * Anoxic_X_I/4
	d_Anoxic_S_O2 -= (Qin + Qsludge + Qinter) * Anoxic_S_O2/4
	d_Anoxic_S_F -= (Qin + Qsludge + Qinter) * Anoxic_S_F/4
	d_Anoxic_S_A -= (Qin + Qsludge + Qinter) * Anoxic_S_A/4
	d_Anoxic_S_NH4 -= (Qin + Qsludge + Qinter) * Anoxic_S_NH4/4
	d_Anoxic_S_NO3 -= (Qin + Qsludge + Qinter) * Anoxic_S_NO3/4
	d_Anoxic_S_I -= (Qin + Qsludge + Qinter) * Anoxic_S_I/4
	d_Anoxic_S_ALK -= (Qin + Qsludge + Qinter) * Anoxic_S_ALK/4
	d_Anoxic_S_N2 -= (Qin + Qsludge + Qinter) * Anoxic_S_N2/4
	d_Anoxic_X_S -= (Qin + Qsludge + Qinter) * Anoxic_X_S/4
	d_Anoxic_X_PAO -= (Qin + Qsludge + Qinter) * Anoxic_X_PAO/4
	d_Anoxic_X_PP -= (Qin + Qsludge + Qinter) * Anoxic_X_PP/4
	d_Anoxic_X_PHA -= (Qin + Qsludge + Qinter) * Anoxic_X_PHA/4
	d_Anoxic_X_H -= (Qin + Qsludge + Qinter) * Anoxic_X_H/4
	d_Anoxic_X_AUT -= (Qin + Qsludge + Qinter) * Anoxic_X_AUT/4
	d_Anoxic_X_TSS -= (Qin + Qsludge + Qinter) * Anoxic_X_TSS/4
	d_Anoxic_S_PO4 -= (Qin + Qsludge + Qinter) * Anoxic_S_PO4/4
	#inflow from Anoxic to Aerobic
	d_Aerobic_X_I += (Qin + Qsludge + Qinter) * Anoxic_X_I/6
	d_Aerobic_S_O2 += (Qin + Qsludge + Qinter) * Anoxic_S_O2/6
	d_Aerobic_S_F += (Qin + Qsludge + Qinter) * Anoxic_S_F/6
	d_Aerobic_S_A += (Qin + Qsludge + Qinter) * Anoxic_S_A/6
	d_Aerobic_S_NH4 += (Qin + Qsludge + Qinter) * Anoxic_S_NH4/6
	d_Aerobic_S_NO3 += (Qin + Qsludge + Qinter) * Anoxic_S_NO3/6
	d_Aerobic_S_I += (Qin + Qsludge + Qinter) * Anoxic_S_I/6
	d_Aerobic_S_ALK += (Qin + Qsludge + Qinter) * Anoxic_S_ALK/6
	d_Aerobic_S_N2 += (Qin + Qsludge + Qinter) * Anoxic_S_N2/6
	d_Aerobic_X_S += (Qin + Qsludge + Qinter) * Anoxic_X_S/6
	d_Aerobic_X_PAO += (Qin + Qsludge + Qinter) * Anoxic_X_PAO/6
	d_Aerobic_X_PP += (Qin + Qsludge + Qinter) * Anoxic_X_PP/6
	d_Aerobic_X_PHA += (Qin + Qsludge + Qinter) * Anoxic_X_PHA/6
	d_Aerobic_X_H += (Qin + Qsludge + Qinter) * Anoxic_X_H/6
	d_Aerobic_X_AUT += (Qin + Qsludge + Qinter) * Anoxic_X_AUT/6
	d_Aerobic_X_TSS += (Qin + Qsludge + Qinter) * Anoxic_X_TSS/6
	d_Aerobic_S_PO4 += (Qin + Qsludge + Qinter) * Anoxic_S_PO4/6
	#outflow from Aerobic
	d_Aerobic_X_I -= (Qin + Qsludge + Qinter) * Aerobic_X_I/6
	d_Aerobic_S_O2 -= (Qin + Qsludge + Qinter) * Aerobic_S_O2/6
	d_Aerobic_S_F -= (Qin + Qsludge + Qinter) * Aerobic_S_F/6
	d_Aerobic_S_A -= (Qin + Qsludge + Qinter) * Aerobic_S_A/6
	d_Aerobic_S_NH4 -= (Qin + Qsludge + Qinter) * Aerobic_S_NH4/6
	d_Aerobic_S_NO3 -= (Qin + Qsludge + Qinter) * Aerobic_S_NO3/6
	d_Aerobic_S_I -= (Qin + Qsludge + Qinter) * Aerobic_S_I/6
	d_Aerobic_S_ALK -= (Qin + Qsludge + Qinter) * Aerobic_S_ALK/6
	d_Aerobic_S_N2 -= (Qin + Qsludge + Qinter) * Aerobic_S_N2/6
	d_Aerobic_X_S -= (Qin + Qsludge + Qinter) * Aerobic_X_S/6
	d_Aerobic_X_PAO -= (Qin + Qsludge + Qinter) * Aerobic_X_PAO/6
	d_Aerobic_X_PP -= (Qin + Qsludge + Qinter) * Aerobic_X_PP/6
	d_Aerobic_X_PHA -= (Qin + Qsludge + Qinter) * Aerobic_X_PHA/6
	d_Aerobic_X_H -= (Qin + Qsludge + Qinter) * Aerobic_X_H/6
	d_Aerobic_X_AUT -= (Qin + Qsludge + Qinter) * Aerobic_X_AUT/6
	d_Aerobic_X_TSS -= (Qin + Qsludge + Qinter) * Aerobic_X_TSS/6
	d_Aerobic_S_PO4 -= (Qin + Qsludge + Qinter) * Aerobic_S_PO4/6
	#inflow from Aerobic to Clarifier
	d_Clarifier_X_I += (Qin - 12/SRT + Qsludge) * Aerobic_X_I/6
	d_Clarifier_S_O2 += (Qin - 12/SRT + Qsludge) * Aerobic_S_O2/6
	d_Clarifier_S_F += (Qin - 12/SRT + Qsludge) * Aerobic_S_F/6
	d_Clarifier_S_A += (Qin - 12/SRT + Qsludge) * Aerobic_S_A/6
	d_Clarifier_S_NH4 += (Qin - 12/SRT + Qsludge) * Aerobic_S_NH4/6
	d_Clarifier_S_NO3 += (Qin - 12/SRT + Qsludge) * Aerobic_S_NO3/6
	d_Clarifier_S_I += (Qin - 12/SRT + Qsludge) * Aerobic_S_I/6
	d_Clarifier_S_ALK += (Qin - 12/SRT + Qsludge) * Aerobic_S_ALK/6
	d_Clarifier_S_N2 += (Qin - 12/SRT + Qsludge) * Aerobic_S_N2/6
	d_Clarifier_X_S += (Qin - 12/SRT + Qsludge) * Aerobic_X_S/6
	d_Clarifier_X_PAO += (Qin - 12/SRT + Qsludge) * Aerobic_X_PAO/6
	d_Clarifier_X_PP += (Qin - 12/SRT + Qsludge) * Aerobic_X_PP/6
	d_Clarifier_X_PHA += (Qin - 12/SRT + Qsludge) * Aerobic_X_PHA/6
	d_Clarifier_X_H += (Qin - 12/SRT + Qsludge) * Aerobic_X_H/6
	d_Clarifier_X_AUT += (Qin - 12/SRT + Qsludge) * Aerobic_X_AUT/6
	d_Clarifier_X_TSS += (Qin - 12/SRT + Qsludge) * Aerobic_X_TSS/6
	d_Clarifier_S_PO4 += (Qin - 12/SRT + Qsludge) * Aerobic_S_PO4/6
	#outflow from Clarifier
	d_Clarifier_X_I -= (Qin - 12/SRT + Qsludge) * Clarifier_X_I/6
	d_Clarifier_S_O2 -= (Qin - 12/SRT + Qsludge) * Clarifier_S_O2/6
	d_Clarifier_S_F -= (Qin - 12/SRT + Qsludge) * Clarifier_S_F/6
	d_Clarifier_S_A -= (Qin - 12/SRT + Qsludge) * Clarifier_S_A/6
	d_Clarifier_S_NH4 -= (Qin - 12/SRT + Qsludge) * Clarifier_S_NH4/6
	d_Clarifier_S_NO3 -= (Qin - 12/SRT + Qsludge) * Clarifier_S_NO3/6
	d_Clarifier_S_I -= (Qin - 12/SRT + Qsludge) * Clarifier_S_I/6
	d_Clarifier_S_ALK -= (Qin - 12/SRT + Qsludge) * Clarifier_S_ALK/6
	d_Clarifier_S_N2 -= (Qin - 12/SRT + Qsludge) * Clarifier_S_N2/6
	d_Clarifier_X_S -= (Qin - 12/SRT + Qsludge) * Clarifier_X_S/6
	d_Clarifier_X_PAO -= (Qin - 12/SRT + Qsludge) * Clarifier_X_PAO/6
	d_Clarifier_X_PP -= (Qin - 12/SRT + Qsludge) * Clarifier_X_PP/6
	d_Clarifier_X_PHA -= (Qin - 12/SRT + Qsludge) * Clarifier_X_PHA/6
	d_Clarifier_X_H -= (Qin - 12/SRT + Qsludge) * Clarifier_X_H/6
	d_Clarifier_X_AUT -= (Qin - 12/SRT + Qsludge) * Clarifier_X_AUT/6
	d_Clarifier_X_TSS -= (Qin - 12/SRT + Qsludge) * Clarifier_X_TSS/6
	d_Clarifier_S_PO4 -= (Qin - 12/SRT + Qsludge) * Clarifier_S_PO4/6
	return d_Influent_S_A, d_Influent_S_ALK, d_Influent_S_F, d_Influent_S_I, d_Influent_S_N2, d_Influent_S_NH4, d_Influent_S_NO3, d_Influent_S_O2, d_Influent_S_PO4, d_Influent_X_AUT, d_Influent_X_H, d_Influent_X_I, d_Influent_X_PAO, d_Influent_X_PHA, d_Influent_X_PP, d_Influent_X_S, d_Influent_X_TSS, d_Anaerobic_S_A, d_Anaerobic_S_ALK, d_Anaerobic_S_F, d_Anaerobic_S_I, d_Anaerobic_S_N2, d_Anaerobic_S_NH4, d_Anaerobic_S_NO3, d_Anaerobic_S_O2, d_Anaerobic_S_PO4, d_Anaerobic_X_AUT, d_Anaerobic_X_H, d_Anaerobic_X_I, d_Anaerobic_X_PAO, d_Anaerobic_X_PHA, d_Anaerobic_X_PP, d_Anaerobic_X_S, d_Anaerobic_X_TSS, d_Anoxic_S_A, d_Anoxic_S_ALK, d_Anoxic_S_F, d_Anoxic_S_I, d_Anoxic_S_N2, d_Anoxic_S_NH4, d_Anoxic_S_NO3, d_Anoxic_S_O2, d_Anoxic_S_PO4, d_Anoxic_X_AUT, d_Anoxic_X_H, d_Anoxic_X_I, d_Anoxic_X_PAO, d_Anoxic_X_PHA, d_Anoxic_X_PP, d_Anoxic_X_S, d_Anoxic_X_TSS, d_Aerobic_S_A, d_Aerobic_S_ALK, d_Aerobic_S_F, d_Aerobic_S_I, d_Aerobic_S_N2, d_Aerobic_S_NH4, d_Aerobic_S_NO3, d_Aerobic_S_O2, d_Aerobic_S_PO4, d_Aerobic_X_AUT, d_Aerobic_X_H, d_Aerobic_X_I, d_Aerobic_X_PAO, d_Aerobic_X_PHA, d_Aerobic_X_PP, d_Aerobic_X_S, d_Aerobic_X_TSS, d_Clarifier_S_A, d_Clarifier_S_ALK, d_Clarifier_S_F, d_Clarifier_S_I, d_Clarifier_S_N2, d_Clarifier_S_NH4, d_Clarifier_S_NO3, d_Clarifier_S_O2, d_Clarifier_S_PO4, d_Clarifier_X_AUT, d_Clarifier_X_H, d_Clarifier_X_I, d_Clarifier_X_PAO, d_Clarifier_X_PHA, d_Clarifier_X_PP, d_Clarifier_X_S, d_Clarifier_X_TSS



def get_dXdt(Influent_S_A, Influent_S_ALK, Influent_S_F, Influent_S_I, Influent_S_N2, Influent_S_NH4, Influent_S_NO3, Influent_S_O2, Influent_S_PO4, Influent_X_AUT, Influent_X_H, Influent_X_I, Influent_X_PAO, Influent_X_PHA, Influent_X_PP, Influent_X_S, Influent_X_TSS, Anaerobic_S_A, Anaerobic_S_ALK, Anaerobic_S_F, Anaerobic_S_I, Anaerobic_S_N2, Anaerobic_S_NH4, Anaerobic_S_NO3, Anaerobic_S_O2, Anaerobic_S_PO4, Anaerobic_X_AUT, Anaerobic_X_H, Anaerobic_X_I, Anaerobic_X_PAO, Anaerobic_X_PHA, Anaerobic_X_PP, Anaerobic_X_S, Anaerobic_X_TSS, Anoxic_S_A, Anoxic_S_ALK, Anoxic_S_F, Anoxic_S_I, Anoxic_S_N2, Anoxic_S_NH4, Anoxic_S_NO3, Anoxic_S_O2, Anoxic_S_PO4, Anoxic_X_AUT, Anoxic_X_H, Anoxic_X_I, Anoxic_X_PAO, Anoxic_X_PHA, Anoxic_X_PP, Anoxic_X_S, Anoxic_X_TSS, Aerobic_S_A, Aerobic_S_ALK, Aerobic_S_F, Aerobic_S_I, Aerobic_S_N2, Aerobic_S_NH4, Aerobic_S_NO3, Aerobic_S_O2, Aerobic_S_PO4, Aerobic_X_AUT, Aerobic_X_H, Aerobic_X_I, Aerobic_X_PAO, Aerobic_X_PHA, Aerobic_X_PP, Aerobic_X_S, Aerobic_X_TSS, Clarifier_S_A, Clarifier_S_ALK, Clarifier_S_F, Clarifier_S_I, Clarifier_S_N2, Clarifier_S_NH4, Clarifier_S_NO3, Clarifier_S_O2, Clarifier_S_PO4, Clarifier_X_AUT, Clarifier_X_H, Clarifier_X_I, Clarifier_X_PAO, Clarifier_X_PHA, Clarifier_X_PP, Clarifier_X_S, Clarifier_X_TSS, Qin, Qsludge, Qinter, Inflow_S_A, Inflow_S_ALK, Inflow_S_F, Inflow_S_I, Inflow_S_N2, Inflow_S_NH4, Inflow_S_NO3, Inflow_S_O2, Inflow_S_PO4, Inflow_X_AUT, Inflow_X_H, Inflow_X_I, Inflow_X_PAO, Inflow_X_PHA, Inflow_X_PP, Inflow_X_S, Inflow_X_TSS, SRT, DO_given):
	# mass flow
	d_Influent_S_A, d_Influent_S_ALK, d_Influent_S_F, d_Influent_S_I, d_Influent_S_N2, d_Influent_S_NH4, d_Influent_S_NO3, d_Influent_S_O2, d_Influent_S_PO4, d_Influent_X_AUT, d_Influent_X_H, d_Influent_X_I, d_Influent_X_PAO, d_Influent_X_PHA, d_Influent_X_PP, d_Influent_X_S, d_Influent_X_TSS, d_Anaerobic_S_A, d_Anaerobic_S_ALK, d_Anaerobic_S_F, d_Anaerobic_S_I, d_Anaerobic_S_N2, d_Anaerobic_S_NH4, d_Anaerobic_S_NO3, d_Anaerobic_S_O2, d_Anaerobic_S_PO4, d_Anaerobic_X_AUT, d_Anaerobic_X_H, d_Anaerobic_X_I, d_Anaerobic_X_PAO, d_Anaerobic_X_PHA, d_Anaerobic_X_PP, d_Anaerobic_X_S, d_Anaerobic_X_TSS, d_Anoxic_S_A, d_Anoxic_S_ALK, d_Anoxic_S_F, d_Anoxic_S_I, d_Anoxic_S_N2, d_Anoxic_S_NH4, d_Anoxic_S_NO3, d_Anoxic_S_O2, d_Anoxic_S_PO4, d_Anoxic_X_AUT, d_Anoxic_X_H, d_Anoxic_X_I, d_Anoxic_X_PAO, d_Anoxic_X_PHA, d_Anoxic_X_PP, d_Anoxic_X_S, d_Anoxic_X_TSS, d_Aerobic_S_A, d_Aerobic_S_ALK, d_Aerobic_S_F, d_Aerobic_S_I, d_Aerobic_S_N2, d_Aerobic_S_NH4, d_Aerobic_S_NO3, d_Aerobic_S_O2, d_Aerobic_S_PO4, d_Aerobic_X_AUT, d_Aerobic_X_H, d_Aerobic_X_I, d_Aerobic_X_PAO, d_Aerobic_X_PHA, d_Aerobic_X_PP, d_Aerobic_X_S, d_Aerobic_X_TSS, d_Clarifier_S_A, d_Clarifier_S_ALK, d_Clarifier_S_F, d_Clarifier_S_I, d_Clarifier_S_N2, d_Clarifier_S_NH4, d_Clarifier_S_NO3, d_Clarifier_S_O2, d_Clarifier_S_PO4, d_Clarifier_X_AUT, d_Clarifier_X_H, d_Clarifier_X_I, d_Clarifier_X_PAO, d_Clarifier_X_PHA, d_Clarifier_X_PP, d_Clarifier_X_S, d_Clarifier_X_TSS = get_mass_flow(Influent_S_A, Influent_S_ALK, Influent_S_F, Influent_S_I, Influent_S_N2, Influent_S_NH4, Influent_S_NO3, Influent_S_O2, Influent_S_PO4, Influent_X_AUT, Influent_X_H, Influent_X_I, Influent_X_PAO, Influent_X_PHA, Influent_X_PP, Influent_X_S, Influent_X_TSS, Anaerobic_S_A, Anaerobic_S_ALK, Anaerobic_S_F, Anaerobic_S_I, Anaerobic_S_N2, Anaerobic_S_NH4, Anaerobic_S_NO3, Anaerobic_S_O2, Anaerobic_S_PO4, Anaerobic_X_AUT, Anaerobic_X_H, Anaerobic_X_I, Anaerobic_X_PAO, Anaerobic_X_PHA, Anaerobic_X_PP, Anaerobic_X_S, Anaerobic_X_TSS, Anoxic_S_A, Anoxic_S_ALK, Anoxic_S_F, Anoxic_S_I, Anoxic_S_N2, Anoxic_S_NH4, Anoxic_S_NO3, Anoxic_S_O2, Anoxic_S_PO4, Anoxic_X_AUT, Anoxic_X_H, Anoxic_X_I, Anoxic_X_PAO, Anoxic_X_PHA, Anoxic_X_PP, Anoxic_X_S, Anoxic_X_TSS, Aerobic_S_A, Aerobic_S_ALK, Aerobic_S_F, Aerobic_S_I, Aerobic_S_N2, Aerobic_S_NH4, Aerobic_S_NO3, Aerobic_S_O2, Aerobic_S_PO4, Aerobic_X_AUT, Aerobic_X_H, Aerobic_X_I, Aerobic_X_PAO, Aerobic_X_PHA, Aerobic_X_PP, Aerobic_X_S, Aerobic_X_TSS, Clarifier_S_A, Clarifier_S_ALK, Clarifier_S_F, Clarifier_S_I, Clarifier_S_N2, Clarifier_S_NH4, Clarifier_S_NO3, Clarifier_S_O2, Clarifier_S_PO4, Clarifier_X_AUT, Clarifier_X_H, Clarifier_X_I, Clarifier_X_PAO, Clarifier_X_PHA, Clarifier_X_PP, Clarifier_X_S, Clarifier_X_TSS, Qin, Qsludge, Qinter, Inflow_S_A, Inflow_S_ALK, Inflow_S_F, Inflow_S_I, Inflow_S_N2, Inflow_S_NH4, Inflow_S_NO3, Inflow_S_O2, Inflow_S_PO4, Inflow_X_AUT, Inflow_X_H, Inflow_X_I, Inflow_X_PAO, Inflow_X_PHA, Inflow_X_PP, Inflow_X_S, Inflow_X_TSS, SRT)
	# chem. reaction@Anaerobic
	d_Anaerobic_S_A_chem,d_Anaerobic_S_ALK_chem,d_Anaerobic_S_F_chem,d_Anaerobic_S_I_chem,d_Anaerobic_S_N2_chem,d_Anaerobic_S_NH4_chem,d_Anaerobic_S_NO3_chem,d_Anaerobic_S_O2_chem,d_Anaerobic_S_PO4_chem,d_Anaerobic_X_AUT_chem,d_Anaerobic_X_H_chem,d_Anaerobic_X_I_chem,d_Anaerobic_X_PAO_chem,d_Anaerobic_X_PHA_chem,d_Anaerobic_X_PP_chem,d_Anaerobic_X_S_chem,d_Anaerobic_X_TSS_chem = get_chem_reaction(Anaerobic_S_A,Anaerobic_S_ALK,Anaerobic_S_F,Anaerobic_S_I,Anaerobic_S_N2,Anaerobic_S_NH4,Anaerobic_S_NO3,Anaerobic_S_O2,Anaerobic_S_PO4,Anaerobic_X_AUT,Anaerobic_X_H,Anaerobic_X_I,Anaerobic_X_PAO,Anaerobic_X_PHA,Anaerobic_X_PP,Anaerobic_X_S,Anaerobic_X_TSS, DO_given, with_aeration = False)
	# chem. reaction@Anoxic
	d_Anoxic_S_A_chem,d_Anoxic_S_ALK_chem,d_Anoxic_S_F_chem,d_Anoxic_S_I_chem,d_Anoxic_S_N2_chem,d_Anoxic_S_NH4_chem,d_Anoxic_S_NO3_chem,d_Anoxic_S_O2_chem,d_Anoxic_S_PO4_chem,d_Anoxic_X_AUT_chem,d_Anoxic_X_H_chem,d_Anoxic_X_I_chem,d_Anoxic_X_PAO_chem,d_Anoxic_X_PHA_chem,d_Anoxic_X_PP_chem,d_Anoxic_X_S_chem,d_Anoxic_X_TSS_chem = get_chem_reaction(Anoxic_S_A,Anoxic_S_ALK,Anoxic_S_F,Anoxic_S_I,Anoxic_S_N2,Anoxic_S_NH4,Anoxic_S_NO3,Anoxic_S_O2,Anoxic_S_PO4,Anoxic_X_AUT,Anoxic_X_H,Anoxic_X_I,Anoxic_X_PAO,Anoxic_X_PHA,Anoxic_X_PP,Anoxic_X_S,Anoxic_X_TSS, DO_given, with_aeration = False)
	# chem. reaction@Aerobic
	d_Aerobic_S_A_chem,d_Aerobic_S_ALK_chem,d_Aerobic_S_F_chem,d_Aerobic_S_I_chem,d_Aerobic_S_N2_chem,d_Aerobic_S_NH4_chem,d_Aerobic_S_NO3_chem,d_Aerobic_S_O2_chem,d_Aerobic_S_PO4_chem,d_Aerobic_X_AUT_chem,d_Aerobic_X_H_chem,d_Aerobic_X_I_chem,d_Aerobic_X_PAO_chem,d_Aerobic_X_PHA_chem,d_Aerobic_X_PP_chem,d_Aerobic_X_S_chem,d_Aerobic_X_TSS_chem = get_chem_reaction(Aerobic_S_A,Aerobic_S_ALK,Aerobic_S_F,Aerobic_S_I,Aerobic_S_N2,Aerobic_S_NH4,Aerobic_S_NO3,Aerobic_S_O2,Aerobic_S_PO4,Aerobic_X_AUT,Aerobic_X_H,Aerobic_X_I,Aerobic_X_PAO,Aerobic_X_PHA,Aerobic_X_PP,Aerobic_X_S,Aerobic_X_TSS, DO_given, with_aeration = True)
	# Anaerobic
	d_Anaerobic_S_A += d_Anaerobic_S_A_chem
	d_Anaerobic_S_ALK += d_Anaerobic_S_ALK_chem
	d_Anaerobic_S_F += d_Anaerobic_S_F_chem
	d_Anaerobic_S_I += d_Anaerobic_S_I_chem
	d_Anaerobic_S_N2 += d_Anaerobic_S_N2_chem
	d_Anaerobic_S_NH4 += d_Anaerobic_S_NH4_chem
	d_Anaerobic_S_NO3 += d_Anaerobic_S_NO3_chem
	d_Anaerobic_S_O2 += d_Anaerobic_S_O2_chem
	d_Anaerobic_S_PO4 += d_Anaerobic_S_PO4_chem
	d_Anaerobic_X_AUT += d_Anaerobic_X_AUT_chem
	d_Anaerobic_X_H += d_Anaerobic_X_H_chem
	d_Anaerobic_X_I += d_Anaerobic_X_I_chem
	d_Anaerobic_X_PAO += d_Anaerobic_X_PAO_chem
	d_Anaerobic_X_PHA += d_Anaerobic_X_PHA_chem
	d_Anaerobic_X_PP += d_Anaerobic_X_PP_chem
	d_Anaerobic_X_S += d_Anaerobic_X_S_chem
	d_Anaerobic_X_TSS += d_Anaerobic_X_TSS_chem
	# Anoxic
	d_Anoxic_S_A += d_Anoxic_S_A_chem
	d_Anoxic_S_ALK += d_Anoxic_S_ALK_chem
	d_Anoxic_S_F += d_Anoxic_S_F_chem
	d_Anoxic_S_I += d_Anoxic_S_I_chem
	d_Anoxic_S_N2 += d_Anoxic_S_N2_chem
	d_Anoxic_S_NH4 += d_Anoxic_S_NH4_chem
	d_Anoxic_S_NO3 += d_Anoxic_S_NO3_chem
	d_Anoxic_S_O2 += d_Anoxic_S_O2_chem
	d_Anoxic_S_PO4 += d_Anoxic_S_PO4_chem
	d_Anoxic_X_AUT += d_Anoxic_X_AUT_chem
	d_Anoxic_X_H += d_Anoxic_X_H_chem
	d_Anoxic_X_I += d_Anoxic_X_I_chem
	d_Anoxic_X_PAO += d_Anoxic_X_PAO_chem
	d_Anoxic_X_PHA += d_Anoxic_X_PHA_chem
	d_Anoxic_X_PP += d_Anoxic_X_PP_chem
	d_Anoxic_X_S += d_Anoxic_X_S_chem
	d_Anoxic_X_TSS += d_Anoxic_X_TSS_chem
	# Aerobic
	d_Aerobic_S_A += d_Aerobic_S_A_chem
	d_Aerobic_S_ALK += d_Aerobic_S_ALK_chem
	d_Aerobic_S_F += d_Aerobic_S_F_chem
	d_Aerobic_S_I += d_Aerobic_S_I_chem
	d_Aerobic_S_N2 += d_Aerobic_S_N2_chem
	d_Aerobic_S_NH4 += d_Aerobic_S_NH4_chem
	d_Aerobic_S_NO3 += d_Aerobic_S_NO3_chem
	d_Aerobic_S_O2 += d_Aerobic_S_O2_chem
	d_Aerobic_S_PO4 += d_Aerobic_S_PO4_chem
	d_Aerobic_X_AUT += d_Aerobic_X_AUT_chem
	d_Aerobic_X_H += d_Aerobic_X_H_chem
	d_Aerobic_X_I += d_Aerobic_X_I_chem
	d_Aerobic_X_PAO += d_Aerobic_X_PAO_chem
	d_Aerobic_X_PHA += d_Aerobic_X_PHA_chem
	d_Aerobic_X_PP += d_Aerobic_X_PP_chem
	d_Aerobic_X_S += d_Aerobic_X_S_chem
	d_Aerobic_X_TSS += d_Aerobic_X_TSS_chem
	return d_Influent_S_A, d_Influent_S_ALK, d_Influent_S_F, d_Influent_S_I, d_Influent_S_N2, d_Influent_S_NH4, d_Influent_S_NO3, d_Influent_S_O2, d_Influent_S_PO4, d_Influent_X_AUT, d_Influent_X_H, d_Influent_X_I, d_Influent_X_PAO, d_Influent_X_PHA, d_Influent_X_PP, d_Influent_X_S, d_Influent_X_TSS, d_Anaerobic_S_A, d_Anaerobic_S_ALK, d_Anaerobic_S_F, d_Anaerobic_S_I, d_Anaerobic_S_N2, d_Anaerobic_S_NH4, d_Anaerobic_S_NO3, d_Anaerobic_S_O2, d_Anaerobic_S_PO4, d_Anaerobic_X_AUT, d_Anaerobic_X_H, d_Anaerobic_X_I, d_Anaerobic_X_PAO, d_Anaerobic_X_PHA, d_Anaerobic_X_PP, d_Anaerobic_X_S, d_Anaerobic_X_TSS, d_Anoxic_S_A, d_Anoxic_S_ALK, d_Anoxic_S_F, d_Anoxic_S_I, d_Anoxic_S_N2, d_Anoxic_S_NH4, d_Anoxic_S_NO3, d_Anoxic_S_O2, d_Anoxic_S_PO4, d_Anoxic_X_AUT, d_Anoxic_X_H, d_Anoxic_X_I, d_Anoxic_X_PAO, d_Anoxic_X_PHA, d_Anoxic_X_PP, d_Anoxic_X_S, d_Anoxic_X_TSS, d_Aerobic_S_A, d_Aerobic_S_ALK, d_Aerobic_S_F, d_Aerobic_S_I, d_Aerobic_S_N2, d_Aerobic_S_NH4, d_Aerobic_S_NO3, d_Aerobic_S_O2, d_Aerobic_S_PO4, d_Aerobic_X_AUT, d_Aerobic_X_H, d_Aerobic_X_I, d_Aerobic_X_PAO, d_Aerobic_X_PHA, d_Aerobic_X_PP, d_Aerobic_X_S, d_Aerobic_X_TSS, d_Clarifier_S_A, d_Clarifier_S_ALK, d_Clarifier_S_F, d_Clarifier_S_I, d_Clarifier_S_N2, d_Clarifier_S_NH4, d_Clarifier_S_NO3, d_Clarifier_S_O2, d_Clarifier_S_PO4, d_Clarifier_X_AUT, d_Clarifier_X_H, d_Clarifier_X_I, d_Clarifier_X_PAO, d_Clarifier_X_PHA, d_Clarifier_X_PP, d_Clarifier_X_S, d_Clarifier_X_TSS
	
def get_initial_condtion():

	Inflow_S_A = 20
	Inflow_S_ALK = 500
	Inflow_S_F = 30
	Inflow_S_I = 30
	Inflow_S_N2 = 15
	Inflow_S_NH4 = 16
	Inflow_S_NO3 = 0
	Inflow_S_O2 = 0
	Inflow_S_PO4 = 3.6
	Inflow_X_AUT = 0
	Inflow_X_H = 30
	Inflow_X_I = 25
	Inflow_X_PAO = 0
	Inflow_X_PHA = 0
	Inflow_X_PP = 0
	Inflow_X_S = 125
	Inflow_X_TSS = 180


#initial condtion @ Aerobic
	Aerobic_S_A = 1
	Aerobic_S_ALK = 4
	Aerobic_S_F = 1
	Aerobic_S_I = 30
	Aerobic_S_N2 = 10
	Aerobic_S_NH4 = 1
	Aerobic_S_NO3 = 5
	Aerobic_S_O2 = 2
	Aerobic_S_PO4 = 1
	Aerobic_X_AUT = 50
	Aerobic_X_H = 500
	Aerobic_X_I = 1000
	Aerobic_X_PAO = 400
	Aerobic_X_PHA = 30
	Aerobic_X_PP = 50
	Aerobic_X_S = 100
	Aerobic_X_TSS = 3000
#initial condtion @ Anaerobic
	Anaerobic_S_A = 1
	Anaerobic_S_ALK = 4
	Anaerobic_S_F = 1
	Anaerobic_S_I = 30
	Anaerobic_S_N2 = 10
	Anaerobic_S_NH4 = 1
	Anaerobic_S_NO3 = 5
	Anaerobic_S_O2 = 2
	Anaerobic_S_PO4 = 1
	Anaerobic_X_AUT = 50
	Anaerobic_X_H = 500
	Anaerobic_X_I = 1000
	Anaerobic_X_PAO = 400
	Anaerobic_X_PHA = 30
	Anaerobic_X_PP = 50
	Anaerobic_X_S = 100
	Anaerobic_X_TSS = 3000
#initial condtion @ Anoxic
	Anoxic_S_A = 1
	Anoxic_S_ALK = 4
	Anoxic_S_F = 1
	Anoxic_S_I = 30
	Anoxic_S_N2 = 10
	Anoxic_S_NH4 = 1
	Anoxic_S_NO3 = 5
	Anoxic_S_O2 = 2
	Anoxic_S_PO4 = 1
	Anoxic_X_AUT = 50
	Anoxic_X_H = 500
	Anoxic_X_I = 1000
	Anoxic_X_PAO = 400
	Anoxic_X_PHA = 30
	Anoxic_X_PP = 50
	Anoxic_X_S = 100
	Anoxic_X_TSS = 3000
#initial condtion @ Clarifier
	Clarifier_S_A = 1
	Clarifier_S_ALK = 4
	Clarifier_S_F = 1
	Clarifier_S_I = 30
	Clarifier_S_N2 = 10
	Clarifier_S_NH4 = 1
	Clarifier_S_NO3 = 5
	Clarifier_S_O2 = 2
	Clarifier_S_PO4 = 1
	Clarifier_X_AUT = 50
	Clarifier_X_H = 500
	Clarifier_X_I = 1000
	Clarifier_X_PAO = 400
	Clarifier_X_PHA = 30
	Clarifier_X_PP = 50
	Clarifier_X_S = 100
	Clarifier_X_TSS = 3000
#initial condtion @ Influent
	Influent_S_A = Inflow_S_A
	Influent_S_ALK = Inflow_S_ALK
	Influent_S_F = Inflow_S_F
	Influent_S_I = Inflow_S_I
	Influent_S_N2 = Inflow_S_N2
	Influent_S_NH4 = Inflow_S_NH4
	Influent_S_NO3 = Inflow_S_NO3
	Influent_S_O2 = Inflow_S_O2
	Influent_S_PO4 = Inflow_S_PO4
	Influent_X_AUT = Inflow_X_AUT
	Influent_X_H = Inflow_X_H
	Influent_X_I = Inflow_X_I
	Influent_X_PAO = Inflow_X_PAO
	Influent_X_PHA = Inflow_X_PHA
	Influent_X_PP = Inflow_X_PP
	Influent_X_S = Inflow_X_S
	Influent_X_TSS = Inflow_X_TSS

	return Influent_S_A, Influent_S_ALK, Influent_S_F, Influent_S_I, Influent_S_N2, Influent_S_NH4, Influent_S_NO3, Influent_S_O2, Influent_S_PO4, Influent_X_AUT, Influent_X_H, Influent_X_I, Influent_X_PAO, Influent_X_PHA, Influent_X_PP, Influent_X_S, Influent_X_TSS, Anaerobic_S_A, Anaerobic_S_ALK, Anaerobic_S_F, Anaerobic_S_I, Anaerobic_S_N2, Anaerobic_S_NH4, Anaerobic_S_NO3, Anaerobic_S_O2, Anaerobic_S_PO4, Anaerobic_X_AUT, Anaerobic_X_H, Anaerobic_X_I, Anaerobic_X_PAO, Anaerobic_X_PHA, Anaerobic_X_PP, Anaerobic_X_S, Anaerobic_X_TSS, Anoxic_S_A, Anoxic_S_ALK, Anoxic_S_F, Anoxic_S_I, Anoxic_S_N2, Anoxic_S_NH4, Anoxic_S_NO3, Anoxic_S_O2, Anoxic_S_PO4, Anoxic_X_AUT, Anoxic_X_H, Anoxic_X_I, Anoxic_X_PAO, Anoxic_X_PHA, Anoxic_X_PP, Anoxic_X_S, Anoxic_X_TSS, Aerobic_S_A, Aerobic_S_ALK, Aerobic_S_F, Aerobic_S_I, Aerobic_S_N2, Aerobic_S_NH4, Aerobic_S_NO3, Aerobic_S_O2, Aerobic_S_PO4, Aerobic_X_AUT, Aerobic_X_H, Aerobic_X_I, Aerobic_X_PAO, Aerobic_X_PHA, Aerobic_X_PP, Aerobic_X_S, Aerobic_X_TSS, Clarifier_S_A, Clarifier_S_ALK, Clarifier_S_F, Clarifier_S_I, Clarifier_S_N2, Clarifier_S_NH4, Clarifier_S_NO3, Clarifier_S_O2, Clarifier_S_PO4, Clarifier_X_AUT, Clarifier_X_H, Clarifier_X_I, Clarifier_X_PAO, Clarifier_X_PHA, Clarifier_X_PP, Clarifier_X_S, Clarifier_X_TSS


def get_default_inflow():
	Inflow_S_A = 20
	Inflow_S_ALK = 500
	Inflow_S_F = 30
	Inflow_S_I = 30
	Inflow_S_N2 = 15
	Inflow_S_NH4 = 16
	Inflow_S_NO3 = 0
	Inflow_S_O2 = 0
	Inflow_S_PO4 = 3.6
	Inflow_X_AUT = 0
	Inflow_X_H = 30
	Inflow_X_I = 25
	Inflow_X_PAO = 0
	Inflow_X_PHA = 0
	Inflow_X_PP = 0
	Inflow_X_S = 125
	Inflow_X_TSS = 180
	return Inflow_S_A,Inflow_S_ALK,Inflow_S_F,Inflow_S_I,Inflow_S_N2,Inflow_S_NH4,Inflow_S_NO3,Inflow_S_O2,Inflow_S_PO4,Inflow_X_AUT,Inflow_X_H,Inflow_X_I,Inflow_X_PAO,Inflow_X_PHA,Inflow_X_PP,Inflow_X_S,Inflow_X_TSS

